### ISSUE TITLE
Warning: Invalid CRT parameters detected

### ISSUE THREAD

**Issue by qimmik** [litecommerce/core#10]
I am getting this (first) error over and over again, but doesn't seem to stop the functionality of the store except to import the catalog. When importing I also get another error (last code) as well as many of the first error. How can I fix this?

Oct 31 22:12:44 XLite [warning] Warning: Invalid CRT parameters detected in ...\modules\lc_connector\litecommerce\var\run\classes\XLite\Core\TranslationDriver\Gettext.php on line 188
Server API: cgi-fcgi;
Request method: GET;
URI: changes 

Oct 31 15:22:55 XLite [error] Exception: XLite\Model\Image\Product\Image::getImageId() - method not exists or invalid getter/setter in ...\modules\lc_connector\litecommerce\var\run\classes\XLite\Model\AEntity.php on line 232
Server API: cgi-fcgi;
Request method: POST;
URI: /modules/lc_connector/litecommerce/admin.php?target=import_export&action=import&;
Backtrace:
    file <compiled classes repository>/classes\XLite\Controller\Admin\ImportExport.php : 1156
    file <compiled classes repository>/classes\XLite\Controller\Admin\ImportExport.php : 849
    file <compiled classes repository>/classes\XLite\Controller\Admin\ImportExport.php : 655
    file <compiled classes repository>/classes\XLite\Controller\Admin\ImportExport.php : 538
    file <compiled classes repository>/classes\XLite\Controller\AControllerAbstract.php : 1028
    file <compiled classes repository>/classes\XLite\Controller\AControllerAbstract.php : 1049
    file <compiled classes repository>/classes\XLite\Controller\Admin\ImportExport.php : 520
    file <compiled classes repository>/classes\XLite\Controller\AControllerAbstract.php : 342
    file <compiled classes repository>/classes\XLite\Controller\Admin\AAdmin.php : 158
    file <compiled classes repository>/classes\XLite.php : 312
    file <compiled classes repository>/classes\XLite.php : 341
    file <lc root>/admin.php : 30

Sorry if this is not in the right place to post this but thanks for any help :) Love the product!!

**Comment by svowl** [comment]
It seems your environment does not support gettext utility. Try to change the translation driver:
1. Open litecommerce-dir/etc/config.php in editor
2. Scroll down and find out the following lines:

;
; Other options
;
[other]
; Translation drive code - auto / gettext / db
translation_driver = auto
1. Replace auto ==> db
2. Remove directory litecommerce-dir/var/locale

**Comment by qimmik** [comment]
Nice! That worked with removing the Gettext errors! But still get the AEntity.php error while importing. Any ideas about that? Thank you so much for the response and help. Do you need more information about my environment to help report or fix this for others? 
P.S. sent an email about the errors also and it was moved into your bug-tracking system: http://bt.litecommerce.com/view.php?id=40537

**Comment by qimmik** [comment]
Got it taken care of! Thank you all so much for the help, support here is great!
