### ISSUE TITLE
Black background for transparency product image

### ISSUE THREAD

**Issue by qimmik** [litecommerce/core#11]
We use a transparent background with our product images, when they show up on the front-end, the images are black with the transparencies. Almost every place the image appears, the background is black. Only place it is transparent is the pop out frame for the detail information mouse over. Where can we change the background of the image to white instead of black?

**Comment by maxmukhin** [comment]
Could you please send us some of such images ?

Thank you.

**Comment by qimmik** [comment]
Sure, here are 4 ^_^ Thank you for the response!

**Comment by maxmukhin** [comment]
The issue has been fixed.
