### ISSUE TITLE
Notice: Undefined offset: 3 in _menu_translate() 

### ISSUE THREAD

**Issue by qimmik** [litecommerce/core#13]
I don't know if this is the place to ask about this error, if not could you direct me to the right place. ^_^

When going to "my profile" and the edit or shortcut tab, I get the following error:
Notice: Undefined offset: 3 in _menu_translate() (line 762 of ...\includes\menu.inc).
Notice: Undefined offset: 3 in _menu_translate() (line 762 of ...\menu.inc).
Notice: Undefined offset: 3 in _menu_translate() (line 768 of ...\menu.inc).

Know how I can fix this?
Thank you for any help! ^_^

**Comment by maxmukhin** [comment]
We will check it.
Thank you for your cooperation.

**Comment by qimmik** [comment]
Thank you! Let me know if you need anything! ^_^

**Comment by svowl** [comment]
It seems Drupal caused these notices. Try to upgrade Drupal and all of its modules and check if notices disappear

**Comment by qimmik** [comment]
Updated the core and checked the modules, no luck. -_-; Still same error.

**Comment by svowl** [comment]
Hmm.. If you sure you have all Drupal part is up-to-date I can only advise to update lc_connector module. But this module is still in sandbox at drupal.org and not available for updates. Please, wait until we switch it to the 'full project' status or download it at https://github.com/litecommerce/lc_connector/downloads

**Comment by svowl** [comment]
We have switched lc_connector to 'full project' status and you can download version 7.x-1.0 here: http://drupal.org/project/lc_connector

**Comment by qimmik** [comment]
Updated the LC Connector yesterday, did not solve the problem. Still getting the notice. I know its not a big problem (since it is just a notice), but wanted to see if you knew anything about it. I will continue to look into it and will post the solution, if any, when I find it. Thanks! ^_^

**Comment by maxmukhin** [comment]
Could you please provide us with the detailed description of how you are reproducing the issue?

Is there any changes in Drupal + LC installation (especially in Drupal: modules, custom changes)?

**Comment by qimmik** [comment]
I have these modules installed with the ones that are enabled indicated. Only custom changes I have made are mostly cosmetic css files and images, with the exception of the changes LC team have advised me to make. I can give you FTP access if needed, but want to make sure it is not displayed publicly. svowl still has the info for the drupal admin access. ^_^

CORE
Aggregator  "7.10"
-Block  "7.10"  ENABLED
Blog    "7.10"
Book    "7.10"
Color   "7.10"
-Comment    "7.10"  ENABLED
-Contact    "7.10"  ENABLED
Content translation "7.10"
-Contextual links   "7.10"  ENABLED
-Dashboard  "7.10"  ENABLED
-Database logging   "7.10"  ENABLED
-Field  "7.10"  ENABLED
-Field SQL storage  "7.10"  ENABLED
-Field UI   "7.10"  ENABLED
-File   "7.10"  ENABLED
-Filter "7.10"  ENABLED
Forum   "7.10"
-Help   "7.10"  ENABLED
-Image  "7.10"  ENABLED
-List   "7.10"  ENABLED
Locale  "7.10"
-Menu   "7.10"  ENABLED
-Node   "7.10"  ENABLED
-Number "7.10"  ENABLED
OpenID  "7.10"
-Options    "7.10"  ENABLED
Overlay "7.10"
-Path   "7.10"  ENABLED
PHP filter  "7.10"
Poll    "7.10"
-RDF    "7.10"  ENABLED
-Search "7.10"  ENABLED
-Shortcut   "7.10"  ENABLED
Statistics  "7.10"
Syslog  "7.10"
-System "7.10"  ENABLED
-Taxonomy   "7.10"  ENABLED
Testing "7.10"
-Text   "7.10"  ENABLED
-Toolbar    "7.10"  ENABLED
Tracker "7.10"
Trigger "7.10"
-Update manager "7.10"  ENABLED
-User   "7.10"  ENABLED

CHAOS TOOL SUITE
Bulk Export "7.x-1.0-alpha2"
Chaos tools "7.x-1.0-alpha2"
Chaos Tools (Ctools) AJAX Example   "7.x-1.0-alpha2"  
Chaos Tools (Ctools) Plugin Example "7.x-1.0-alpha2"  
Custom content panes    "7.x-1.0-alpha2"
Custom rulesets "7.x-1.0-alpha2"
Page manager    "7.x-1.0-alpha2"
Stylizer    "7.x-1.0-alpha2"
Views content panes "7.x-1.0-alpha2"

MAIL
Simplenews  "7.x-1.x-dev"
Simplenews action   "7.x-1.x-dev"
-SMTP Authentication Support    "7.x-1.0-beta1" ENABLED

OTHER
-LC connector       ENABLED
Meta tag simple
Page Title  "7.x-2.4-beta1"
Token   "7.x-1.0-beta1"

SPAM CONTROL
CAPTCHA "7.x-1.0-alpha2"
Image CAPTCHA   "7.x-1.0-alpha2"

STATISTICS
Google Analytics "7.x-1.2"

USER INTERFACE
-jQuery Update  "7.x-2.2"   ENABLED
Wysiwyg "7.x-2.0"

VIEWS
Views   "7.x-3.0-alpha1"
Views exporter  "7.x-3.0-alpha1"
Views UI    "7.x-3.0-alpha1"

**Comment by kerasai** [comment]
I stumbled upon the same error while configuring the path on a View's page.  I had an optional argument as the last item in the path and when I tried to load the page without providing the argument I got this error.  Losing the placeholder at the end cleared it up.  I'd recommend looking at the paths your hook_menu().

The bad path: user/%/events/% (intended to pass uid and date in the url)
The good path: user/%/events (the page callback can accept the date if provided, even without the placeholder)

If you have trouble figuring out which path is having the problem, throw a debug_print_backtrace() in the function that's throwing the errors.  It will print the full function stack along with the arguments passed to each one.  It should be easy to figure out from there.  Yes, it's a core file, and no it's not hacking core if you take it out when you're done.

**Comment by svowl** [comment]
> Views "7.x-3.0-alpha1"

The latest version of this module is 7.x-3.1. Qimmik, try update this and all the rest modules which are enabled in your Drupal.
I can't reproduce this notice on my Drupal+LC installation

**Comment by qimmik** [comment]
I don't have views module enabled, but upgraded it anyway ^_^
I will try will-at-kerasai idea, thanks for the help! Will let you know what I find! ^_^

**Comment by qimmik** [comment]
Reinstalling Drupal+LC3 fixed the problem. Did not find a solution except to reinstall.
