### ISSUE TITLE
LiteCommerce installation status: There are no profiles found in the database

### ISSUE THREAD

**Issue by qimmik** [litecommerce/core#16]
Noticed today that on the Drupal status page, I get this message: "LiteCommerce installation status. There are no profiles found in the database. The installed LiteCommerce software not found. It is required to install LiteCommerce and specify correct path to them in the LC Connector module settings."
I was trying to remember how to link LC to Drupal or synchronize them, but cannot remember or find out how. Help me to remember please. -_-; hehe
Everything is working great, Drupal and LC3 are functioning correctly and all is well. Just get that error.

Thank you!!

**Comment by svowl** [comment]
In earlier versions of Ecommerce CMS the record about installation profile was disabled in the Drupal's system table just after installation complete. We have fixed this. You may ignore this message or you can try the following to avoid it:

In the MySQL console (or PHPMyAdmin) run the following SQL query:
select filename, name, type, status from drupal_system where filename like '%litecommerce%';

If the record will be found with status = 0, then try to update this status to 1 and check if the message disappears.

Please, MAKE A DATABASE BACKUP before this changes.

**Comment by qimmik** [comment]
Hehe, the record found was with status 1 ('profiles/litecommerce/litecommerce.profile', 'litecommerce', 'module', '1').
Only problem it seems to cause (which is minor right now), is that I cannot run the update.php script. The error appears and says it needs to be fixed before proceeding.

**Comment by svowl** [comment]
This is very strange... If it is possible for you to provide us with access to your site, please, post a ticket to http://bt.litecommerce.com (choose 'Support communications' category for the ticket). The first of all we need access to the Drupal admin interface.

**Comment by svowl** [comment]
Fixed. Thank you for the feedback!

**Comment by qimmik** [comment]
Thank You for the help and the patch! 
You all provide wonderful help!
Thank you for the work and customer service.
