### ISSUE TITLE
Bug detected with Internet Explorer 7

### ISSUE THREAD

**Issue by celvin** [litecommerce/core#2]
Tested with:
Server Centos 5
1024 RAM
PHP 5.3.5

The problem is in the client Internet Explorer 7.0.5037.11

Screenshots:
http://img405.imageshack.us/img405/9186/lc3bx.jpg

http://img860.imageshack.us/img860/4376/lc3berrr.jpg

**Comment by maxmukhin** [comment]
Have you installed LC from GIT or from litecommerce site?

**Comment by maxmukhin** [comment]
The issues have been fixed.
Thank you for your cooperation.

**Comment by celvin** [comment]
from website and git, 
now I will to try, thanks.
Good work!
