### ISSUE TITLE
Incorrect URLs when installed with non-standard port

### ISSUE THREAD

**Issue by voloships** [litecommerce/core#27]
All urls that have /litecommerce/ in their path are broken, if LiteCommerce host URL contains port definition.
e.g.: https://example.com:8080/litecommerce/images/category/demo_c14015.jpeg appears as https://example.com/litecommerce/images/category/demo_c14015.jpeg
The same situation with links to litecommerce pages, javascript, css files:
e.g: http://example.com/litecommerce/admin.php?drupalReturnURL=https%3A%2F%2Fexample.com%3A8080%2F instead of http://example.com:8080/litecommerce/admin.php?drupalReturnURL=https%3A%2F%2Fexample.com%3A8080%2F

**Comment by svowl** [comment]
Please check [host_details] section in the file litecommerce/etc/config.php:

[host_details]
http_host = "example.com:8080"
https_host = "example.com:8080"
web_dir = "/litecommerce"

**Comment by voloships** [comment]
Thanks, it helped.
Is it expected behavior and opened issue redundant?

**Comment by svowl** [comment]
When you installed ECommerceCMS did you use URL like https://example.com:8080/install.php or https://example.com/install.php ?

**Comment by voloships** [comment]
Definitely the first one. In other way I would get to other vhost.

**Comment by svowl** [comment]
Thank you for the details. I've reported bug to our bugtracker. We will check it and release the fix in one of next versions.
