### ISSUE TITLE
"Cache rebuild is already started, please wait" every fresh rebuild

### ISSUE THREAD

**Issue by voloships** [litecommerce/core#29]
After installing of last Lite Commerce version and some time of its using, I'm getting the following message for every try of cache update:

ERROR: "-1" (code N/A)

Cache rebuild is already started, please wait

It happens even after cleanup in var/run and manually removing of cache rebuild locks (according to sources). Also I noticed that cache is rebuilded even after such error.

**Comment by svowl** [comment]
You should also delete file var/.rebuildStarted

**Comment by voloships** [comment]
It's autoremoved when error appears.

**Comment by svowl** [comment]
It seems other visitors open your site while you run the cache generating routine. Try to do the following:
1. Close your site with http-authorization
2. Remove var/run and var/.rebuildStarted
3. Open any site page
4. Remove http-authorization

This should help.

**Comment by voloships** [comment]
Yeah, it helped. Thanks.
Strange, because I'm only one user, site is in development and in a intranet.
