### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by ferrynl** [litecommerce/core#3]
Hi,

I get this sql error by Re-building cache, please wait...
ERROR: "0" (code N/A)

SQLSTATE[HY000]: General error: 1005 Can't create table 'testnl.#sql-706f_b714' (errno: 121) SQL query: ALTER TABLE `xlite_form_ids` ADD CONSTRAINT `formid_to_session` FOREIGN KEY `session_id` (`session_id`) REFERENCES `xlite_sessions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE

[05-Apr-2011 23:58:39] Error (code: 0): SQLSTATE[HY000]: General error: 1005 Can't create table 'testnl.#sql-706f_b714' (errno: 121)
SQL query: ALTER TABLE `xlite_form_ids` ADD CONSTRAINT `formid_to_session` FOREIGN KEY `session_id` (`session_id`) REFERENCES `xlite_sessions` (`id`) ON DELETE CASCADE ON UPDAT$
Server API: cgi-fcgi;
Request method: GET;
URI: /osw/xlite/src/cart.php;
Backtrace:
        /home/customers/hk/c/test.nl/html/test.nl/osw/xlite/src/var/run/classes/XLite/Core/Database.php : 724
        /home/customers/hk/c/test.nl/html/test.nl/osw/xlite/src/var/run/classes/XLite/Core/Database.php : 695
        /home/customers/hk/c/test.nl/html/test.nl/osw/xlite/src/Includes/Decorator/Plugin/Doctrine/Plugin/UpdateSchema/Main.php : 50
        /home/customers/hk/c/test.nl/html/test.nl/osw/xlite/src/Includes/Decorator/Utils/PluginManager.php : 80
        /home/customers/hk/c/test.nl/html/test.nl/osw/xlite/src/Includes/Decorator/Utils/CacheManager.php : 480
        Includes\Decorator\Utils\CacheManager::executeStepHandlerThird()
        /home/customers/hk/c/test.nl/html/test.nl/osw/xlite/src/Includes/Utils/Operator.php : 163
        /home/customers/hk/c/test.nl/html/test.nl/osw/xlite/src/Includes/Decorator/Utils/CacheManager.php : 385
        /home/customers/hk/c/test.nl/html/test.nl/osw/xlite/src/Includes/Decorator/Utils/CacheManager.php : 404
        /home/customers/hk/c/test.nl/html/test.nl/osw/xlite/src/Includes/Decorator/Utils/CacheManager.php : 497
        /home/customers/hk/c/test.nl/html/test.nl/osw/xlite/src/top.inc.PHP53.php : 94
        /home/customers/hk/c/test.nl/html/test.nl/osw/xlite/src/top.inc.php : 41
        /home/customers/hk/c/test.nl/html/test.nl/osw/xlite/src/cart.php : 32

Install
git clone http://github.com/litecommerce/core.git xlite
cd xlite
git checkout -b master-dev origin/master-dev
cd ..
cp xlite/src/etc/config.php xlite/src/etc/config.local.php
nano xlite/src/etc/config.local.php
chmod 777 xlite/src/var xlite_cms/sites
cd xlite/src
php -f restoredb demo
http://test.nl/osw/xlite/src/cart.php

**Comment by maxmukhin** [comment]
I have written some kind of quick start manual in Facebook:
http://www.facebook.com/note.php?note_id=180505148668888

Please check your installation.

**Comment by maxmukhin** [comment]
It seems that the issue is resolved...
If it is not please contact to us.
