### ISSUE TITLE
Hacked

### ISSUE THREAD

**Issue by ebaiden** [litecommerce/core#36]
I'm not sure, but I tried to login today to access my backend it said 
Error:There is no user with specified email address 

Even when I tried to retrieve the password using my email address, it still said the same thing. 
I then didn't type anything on the empty field and then it displayed the message 

Recover password
The confirmation URL link was mailed to 

yeah... seriously, that's what it said. Blank. What should I do?

**Comment by ebaiden** [comment]
Help? Anyone?

**Comment by fundaev** [comment]
Please refer to http://bt.litecommerce.com/view.php?id=42066 ticket.
