### ISSUE TITLE
Product Options are Not Displayed For Admin Invoice

### ISSUE THREAD

**Issue by StefanBossbaly** [litecommerce/core#4]
First off sorry if I am in the wrong place. 

The bug is that when a customer orders and item with options (color, size ...) the invoice for the product displays the options that the customer order (http://dl.dropbox.com/u/322509/Customer%20View.png) however when the admin logs into the "Administrator panel" and displays the order the product options are not displayed (http://dl.dropbox.com/u/322509/Admin%20View.png). However if the customer order multiply items with different options they are separated in the admin invoice.

**Comment by maxmukhin** [comment]
Thank you for your help.

We will check it.

**Comment by maxmukhin** [comment]
We have added the product options block in the admin invoice:

https://github.com/litecommerce/core/commit/f003cfd63674d3b70d3f78ba567125651005ac87
