### ISSUE TITLE
Error on install - at step five

### ISSUE THREAD

**Issue by stdave** [litecommerce/core#46]
I am attempting to install the stand-alone version of litecommerce.

While installing I get the following error at step 5 of the installation;

ERROR: "Includes\ErrorHandler::FATAL_ERROR" (code 2)
Call to undefined function Includes\Decorator\Utils\token_get_all()

Looking in the httpd_errors log I see the following;

PHP Fatal error:  Call to undefined function Includes\Decorator\Utils\token_get_all() in /usr/hosting/3s1.com/litecommerce/Includes/Decorator/Utils/Tokenizer.php on line 500, referer: http://3s1.com/litecommerce/install.php

The part may be unimportant buy I'll mention it anyway;
On install all checkouts seemed fine with one exception;

Under non-critical dependancies the line
Disabled functions - indicates "failed" although all sections below that are checked as fine.
While reading the page it seems to indicate that I should click the "failed" to fine out more information, it does not appear to be a link.

Any pointers would be helpful.

**Comment by svowl** [comment]
Please make sure the Tokenizer extension is not disabled in your PHP configuration (http://www.php.net/manual/en/book.tokenizer.php) and function 'token_get_all' is not included to the disable_functions option in php.ini file. We will check why 'disabled functions' does not display the list of functions. Thank you

**Comment by svowl** [comment]
Ticket: http://bt.litecommerce.com/view.php?id=42288

**Comment by fundaev** [comment]
If our assistance is still required here, please, let us know.
