### ISSUE TITLE
Password Length and PCI Compliance Issues

### ISSUE THREAD

**Issue by RapidTransit** [litecommerce/core#7]
LC's target audience will most likely involve Small Business users who will use their own credit card terminal for manual credit card entry in the default install I was allowed to make a user: 'root@localhost.com' with a Password: 'root' at installation. At issue is PCI DSS v2 Sections 8.5.9 - 8.5.15  a password best practice when handling potentially sensitive data whether PCI compliance even matters or not.

I haven't personally went through all of LC for PCI Issues if a summary is needed one can be rovided.

**Comment by maxmukhin** [comment]
There will be no manual card processing payments in LC.

If there is a manual processing then LC must be PA-DSS and PCI-DSS certified. 
This certification costs a lot of money. 

Actually there is a programming product from our partner: X-Payments which is PA-DSS and PCI-DSS certified, 
http://www.x-cart.com/x-payments.html

Thank you.
