### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by samzhao** [litecommerce/core#8]
When I was trying to backup Litecommerce (connected to Drupal), the system recommended me to put the store in maintenance mode in the "General Settings" before backing up. However, there doesn't seem to have anything related to maintenance mode or catalog mode in the "General Settings". How can I effectively back up Litecommerce? Do I still have to make a backup of Drupal after backing up Litecommerce?

**Comment by svowl** [comment]
LiteCommerce knows nothing about Drupal and cannot backup its database. So, if you need to backup a whole site you should do it separately for Drupal and LiteCommerce.

Regarding recommendation to put the store in maintenance mode in the "General Settings" - this text should not direct to this section as this option is hidden when DrupalConnector module enabled. We will fix it, thank you for the report!

**Comment by svowl** [comment]
> Regarding recommendation to put the store in maintenance mode in the "General Settings" - this text should not direct to this section as this option is hidden when DrupalConnector module enabled.

This was fixed in one of previous releases. Thank you!
