### ISSUE TITLE
LiteCommerce software not found in ./modules/lc-connect/litecommerce

### ISSUE THREAD

**Issue by vasundhar** [litecommerce/core#9]
I have preinstalled drupal amd moved lc-connect,litecommerce to site/all/modules and was trying to enable the modules as 
explained however when I select LC Connect in drupal modules I get "LiteCommerce software not found in ./modules/lc-connect/litecommerce" Error

I checked to see if there is a folder and filed by that name and they were there .

**Comment by svowl** [comment]
Ecommerce CMS package contains lc_connector module within drupal/modules/ directory. Installation profile checks this location, not sites/all/modules. You should not modify this if you want install your site from Ecommerce CMS package.
If you selected to install Drupal and LiteCommerce separately you should install Drupal and LiteCommerce and then enable lc_connector module. Please read https://github.com/litecommerce/core/wiki/Installing-LiteCommerce about installing LiteCommerce to an existing Drupal site.
